// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -package=k8s -destination=service_mock.go
//

// Package k8s is a generated GoMock package.
package k8s

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
)

// MockServiceHelper is a mock of ServiceHelper interface.
type MockServiceHelper struct {
	ctrl     *gomock.Controller
	recorder *MockServiceHelperMockRecorder
	isgomock struct{}
}

// MockServiceHelperMockRecorder is the mock recorder for MockServiceHelper.
type MockServiceHelperMockRecorder struct {
	mock *MockServiceHelper
}

// NewMockServiceHelper creates a new mock instance.
func NewMockServiceHelper(ctrl *gomock.Controller) *MockServiceHelper {
	mock := &MockServiceHelper{ctrl: ctrl}
	mock.recorder = &MockServiceHelperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceHelper) EXPECT() *MockServiceHelperMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockServiceHelper) Create(ctx context.Context, namespace string, service *v1.Service) (*v1.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, namespace, service)
	ret0, _ := ret[0].(*v1.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockServiceHelperMockRecorder) Create(ctx, namespace, service any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockServiceHelper)(nil).Create), ctx, namespace, service)
}

// Delete mocks base method.
func (m *MockServiceHelper) Delete(ctx context.Context, namespace, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, namespace, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceHelperMockRecorder) Delete(ctx, namespace, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockServiceHelper)(nil).Delete), ctx, namespace, name)
}

// Get mocks base method.
func (m *MockServiceHelper) Get(ctx context.Context, namespace, name string) (*v1.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, namespace, name)
	ret0, _ := ret[0].(*v1.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockServiceHelperMockRecorder) Get(ctx, namespace, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockServiceHelper)(nil).Get), ctx, namespace, name)
}

// List mocks base method.
func (m *MockServiceHelper) List(ctx context.Context, namespace string) (*v1.ServiceList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, namespace)
	ret0, _ := ret[0].(*v1.ServiceList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockServiceHelperMockRecorder) List(ctx, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockServiceHelper)(nil).List), ctx, namespace)
}

// Update mocks base method.
func (m *MockServiceHelper) Update(ctx context.Context, namespace string, service *v1.Service) (*v1.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, namespace, service)
	ret0, _ := ret[0].(*v1.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockServiceHelperMockRecorder) Update(ctx, namespace, service any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockServiceHelper)(nil).Update), ctx, namespace, service)
}
